language: ruby
rvm:
  - "2.0.0"
before_script:
  - mysql -e 'create database exoplanets_test;'
  - bundle install
  - bundle exex rake db:schema:load
branches:
  only:
    - master

script: bundle exec rake